display_name: Coppelia
icon: assets/logo.png
vendor: Jordan Matelsky
packager: Jordan Matelsky
packagerEmail: coppelia@matelsky.com
license: Apache 2.0
url: https://github.com/j6k4m8/coppelia

build_arch: x86_64

requires:
  - mpv-libs
  - gtk3

keywords:
  - Music
  - Jellyfin
  - Streaming

generic_name: Music Streaming Client

categories:
  - AudioVideo
  - Music

startup_notify: true
